name: news_c17_online
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.0
  dio: ^5.9.1
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  pretty_dio_logger: ^1.4.0
  loader_overlay: ^5.0.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.5
  injectable: ^2.7.1+4
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.9.0
  build_runner: ^2.11.0
flutter:

  uses-material-design: true
  assets:
    - assets/images/